---
- name: Deploy to Minikube
  hosts: localhost
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_installed
      ignore_errors: yes

    - name: Install kubectl if not installed
      apt:
        name: kubectl
        state: present
      when: kubectl_installed.rc != 0

    - name: Apply backend deployment
      shell: kubectl apply -f ../kubernetes-config/deployment.yaml
      register: apply_result

    - name: Display apply result
      debug:
        msg: "Deployment result: {{ apply_result.stdout }}"

    - name: Fail if apply failed
      fail:
        msg: "Applying backend deployment failed"
      when: apply_result.rc != 0
