# apiVersion: v1
# kind: Service
# metadata:
#   name: spefinal-service
# spec:
#   selector:
#     app: spefinal-app
#   ports:
#     - protocol: "TCP"
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spefinal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spefinal-app
  template:
    metadata:
      labels:
        app: spefinal-app
    spec:
      containers:
        - name: spefinal-container
          image: drishti979/spefinal:latest
          ports:
            - containerPort: 5000
