---
- name: Deploying BlossomCare on the Kubernetes cluster
  hosts: localhost
  remote_user: drishti
  become: false
  tasks:
    - name: Fix permissions on .minikube directory
      ansible.builtin.shell: |
        sudo chown -R $USER:$USER $HOME/.minikube
        sudo chmod -R u+wrx $HOME/.minikube

    - name: Start Minikube
      ansible.builtin.shell: |
        minikube start
        
    - name: Wait for Minikube to start completely
      ansible.builtin.wait_for_connection:
      timeout: 600
      delegate_to: localhost

    - name: Ensure Kubernetes context is set
      ansible.builtin.shell: |
        export KUBECONFIG=/var/lib/jenkins/.minikube/profiles/minikube/config
        kubectl config use-context minikube
      
    
        
    - name: Deploying  to Kubernetes cluster
      ansible.builtin.shell: |
        export KUBECONFIG=/var/lib/jenkins/.minikube/profiles/minikube/config
        kubectl create namespace my-app || true
        kubectl config set-context --current --namespace=my-app
        kubectl apply -f ../manifest/deployment.yaml -n my-app
      
    
    - name: Port forward backend service
      ansible.builtin.shell: |
        export KUBECONFIG=/var/lib/jenkins/.minikube/profiles/minikube/config
        pgrep -f "kubectl port-forward service/backend 8085:8085 -n my-app" || nohup kubectl port-forward service/backend 8085:8085 -n my-app > /dev/null 2>&1 &
